command: ["npm", "run", "start"]
runtime: nodejs20

env:
  - name: DATABRICKS_SERVING_ENDPOINT
    valueFrom: serving-endpoint
  - name: PGHOST
    value: "ep-curly-wildflower-d1sc5iwr.database.us-west-2.cloud.databricks.com"
  - name: PGDATABASE
    value: "databricks_postgres"
  - name: PGPORT
    value: "5432"
  - name: PGUSER
    value: "6b555189-5a6a-4788-90d8-0fea08791144"
  - name: PGSSLMODE
    value: require
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: experiment
