command: ["uv", "run", "start-app"]

env:
  - name: API_PROXY
    value: "http://localhost:8080/invocations"
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: experiment
  - name: LAKEBASE_ENDPOINT
    valueFrom: postgres
